imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
		
checks:
    php:
        code_rating: true
        duplication: true
